export interface Student {
  id: string;
  name: string;
  grade: string;
  gender: string;
  dob: string;
  phone: string;
  email: string;
  address: string;
  parentName: string;
  parentPhone: string;
  parentEmail?: string;
  status: string;
  joined: string;
  avatar: string;
  avatarBg: string;
}

export const allStudents: Student[] = [
  {
    id: "S001",
    name: "Amelia Johnson",
    grade: "Grade 10",
    gender: "Female",
    dob: "2009-03-15",
    phone: "+1 555 0101",
    email: "amelia.j@westwood.edu",
    address: "42 Maple Ave, Springfield",
    parentName: "Robert Johnson",
    parentPhone: "+1 555 0100",
    status: "Active",
    joined: "2022-09-01",
    avatar: "AJ",
    avatarBg: "bg-indigo-500",
  },
  {
    id: "S002",
    name: "Marcus Williams",
    grade: "Grade 8",
    gender: "Male",
    dob: "2011-07-22",
    phone: "+1 555 0102",
    email: "marcus.w@westwood.edu",
    address: "88 Oak Street, Springfield",
    parentName: "Denise Williams",
    parentPhone: "+1 555 0103",
    status: "Active",
    joined: "2023-09-01",
    avatar: "MW",
    avatarBg: "bg-emerald-500",
  },
  {
    id: "S003",
    name: "Sofia Rodriguez",
    grade: "Grade 11",
    gender: "Female",
    dob: "2008-11-04",
    phone: "+1 555 0104",
    email: "sofia.r@westwood.edu",
    address: "15 Birch Lane, Springfield",
    parentName: "Carlos Rodriguez",
    parentPhone: "+1 555 0105",
    status: "Active",
    joined: "2021-09-01",
    avatar: "SR",
    avatarBg: "bg-amber-500",
  },
  {
    id: "S004",
    name: "Ethan Chen",
    grade: "Grade 9",
    gender: "Male",
    dob: "2010-05-30",
    phone: "+1 555 0106",
    email: "ethan.c@westwood.edu",
    address: "7 Pine Road, Springfield",
    parentName: "Li Chen",
    parentPhone: "+1 555 0107",
    status: "Inactive",
    joined: "2022-09-01",
    avatar: "EC",
    avatarBg: "bg-rose-500",
  },
  {
    id: "S005",
    name: "Priya Patel",
    grade: "Grade 12",
    gender: "Female",
    dob: "2007-08-19",
    phone: "+1 555 0108",
    email: "priya.p@westwood.edu",
    address: "99 Cedar Blvd, Springfield",
    parentName: "Raj Patel",
    parentPhone: "+1 555 0109",
    status: "Active",
    joined: "2020-09-01",
    avatar: "PP",
    avatarBg: "bg-purple-500",
  },
  {
    id: "S006",
    name: "James Thompson",
    grade: "Grade 7",
    gender: "Male",
    dob: "2012-02-11",
    phone: "+1 555 0110",
    email: "james.t@westwood.edu",
    address: "33 Elm Way, Springfield",
    parentName: "Sarah Thompson",
    parentPhone: "+1 555 0111",
    status: "Active",
    joined: "2024-09-01",
    avatar: "JT",
    avatarBg: "bg-pink-500",
  },
  {
    id: "S007",
    name: "Layla Hassan",
    grade: "Grade 10",
    gender: "Female",
    dob: "2009-12-28",
    phone: "+1 555 0112",
    email: "layla.h@westwood.edu",
    address: "21 Willow Dr, Springfield",
    parentName: "Omar Hassan",
    parentPhone: "+1 555 0113",
    status: "Active",
    joined: "2022-09-01",
    avatar: "LH",
    avatarBg: "bg-sky-500",
  },
  {
    id: "S008",
    name: "Noah Anderson",
    grade: "Grade 8",
    gender: "Male",
    dob: "2011-04-07",
    phone: "+1 555 0114",
    email: "noah.a@westwood.edu",
    address: "55 Aspen Court, Springfield",
    parentName: "Claire Anderson",
    parentPhone: "+1 555 0115",
    status: "Active",
    joined: "2023-09-01",
    avatar: "NA",
    avatarBg: "bg-teal-500",
  },
];
