export const parents = [
  {
    id: "P001",
    name: "Robert Johnson",
    email: "r.johnson@email.com",
    phone: "+1 555 0100",
    address: "42 Maple Ave, Springfield",
    children: ["Amelia Johnson"],
    occupation: "Engineer",
    avatar: "RJ",
    avatarColor: "#6366F1",
  },
  {
    id: "P002",
    name: "Denise Williams",
    email: "d.williams@email.com",
    phone: "+1 555 0103",
    address: "88 Oak Street, Springfield",
    children: ["Marcus Williams"],
    occupation: "Teacher",
    avatar: "DW",
    avatarColor: "#10B981",
  },
  {
    id: "P003",
    name: "Carlos Rodriguez",
    email: "c.rodriguez@email.com",
    phone: "+1 555 0105",
    address: "15 Birch Lane, Springfield",
    children: ["Sofia Rodriguez"],
    occupation: "Business Owner",
    avatar: "CR",
    avatarColor: "#F59E0B",
  },
  {
    id: "P004",
    name: "Li Chen",
    email: "li.chen@email.com",
    phone: "+1 555 0107",
    address: "7 Pine Road, Springfield",
    children: ["Ethan Chen"],
    occupation: "Doctor",
    avatar: "LC",
    avatarColor: "#EF4444",
  },
  {
    id: "P005",
    name: "Raj Patel",
    email: "raj.patel@email.com",
    phone: "+1 555 0109",
    address: "99 Cedar Blvd, Springfield",
    children: ["Priya Patel"],
    occupation: "Accountant",
    avatar: "RP",
    avatarColor: "#8B5CF6",
  },
  {
    id: "P006",
    name: "Sarah Thompson",
    email: "s.thompson@email.com",
    phone: "+1 555 0111",
    address: "33 Elm Way, Springfield",
    children: ["James Thompson"],
    occupation: "Nurse",
    avatar: "ST",
    avatarColor: "#EC4899",
  },
  {
    id: "P007",
    name: "Omar Hassan",
    email: "o.hassan@email.com",
    phone: "+1 555 0113",
    address: "21 Willow Dr, Springfield",
    children: ["Layla Hassan"],
    occupation: "Architect",
    avatar: "OH",
    avatarColor: "#0EA5E9",
  },
  {
    id: "P008",
    name: "Claire Anderson",
    email: "c.anderson@email.com",
    phone: "+1 555 0115",
    address: "55 Aspen Court, Springfield",
    children: ["Noah Anderson"],
    occupation: "Lawyer",
    avatar: "CA",
    avatarColor: "#14B8A6",
  },
];
