export const ROUTES = {
  PUBLIC: {
    HOME: "/",
    LOGIN: "/login",
    FORGOT_PASSWORD: "/forgot-password",
  },
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    STUDENTS: "/admin/students",
    STUDENT_ADD: "/admin/students/add",
    STUDENT_DETAIL: (id: string) => `/admin/students/${id}`,
    TEACHERS: "/admin/teachers",
    TEACHER_DETAIL: (id: string) => `/admin/teachers/${id}`,
    PARENTS: "/admin/parents",
    PARENT_DETAIL: (id: string) => `/admin/parents/${id}`,
    ATTENDANCE: "/admin/attendance",
    ATTENDANCE_CLASSES: "/admin/attendance/classes",
    ATTENDANCE_TEACHERS: "/admin/attendance/teachers",
    ATTENDANCE_MARK: "/admin/attendance/mark",
    ATTENDANCE_REPORT: "/admin/attendance/report",
    ANNOUNCEMENTS: "/admin/announcements",
    ANNOUNCEMENT_CREATE: "/admin/announcements/create",
    ANNOUNCEMENT_DETAIL: (id: string) => `/admin/announcements/${id}`,
    ACADEMICS: "/admin/academics",
    TIMETABLE: "/admin/timetable",
    SESSIONS: "/admin/sessions",
    SETTINGS: "/admin/settings",
  },
  TEACHER: {
    DASHBOARD: "/teacher/dashboard",
    CLASSES: "/teacher/classes",
    CLASS_DETAIL: (id: string) => `/teacher/classes/${id}`,
    ASSIGNMENTS: "/teacher/assignments",
    ATTENDANCE: "/teacher/attendance",
    ANNOUNCEMENTS: "/teacher/announcements",
    GRADES: "/teacher/grades",
    STUDENTS: "/teacher/students",
    // MESSAGES: '/teacher/messages',
    TIMETABLE: "/teacher/timetable",
    PROFILE: "/teacher/profile",
    SETTINGS: "/teacher/settings",
  },
  STUDENT: {
    DASHBOARD: "/student/dashboard",
  },
  PARENT: {
    DASHBOARD: "/parent/dashboard",
    CHILDREN: "/parent/children",
    ATTENDANCE: "/parent/attendance",
    ASSIGNMENTS: "/parent/assignments",
    RESULTS: "/parent/results",
    ANNOUNCEMENTS: "/parent/announcements",
    NOTIFICATIONS: "/parent/notifications",
    PROFILE: "/parent/profile",
  },
} as const;
