export const teachersList = [
  {
    id: "T001",
    name: "Dr. Eleanor Kim",
    dept: "Science & Engineering",
    title: "Head of Science Department",
    email: "e.kim@westwood.edu",
    phone: "+1 555 0180",
    classrooms: 4,
    experience: "12 Years",
    avatar: "EK",
    avatarColor: "bg-indigo-500",
  },
  {
    id: "T002",
    name: "Mr. James Osei",
    dept: "Science & Engineering",
    title: "Lead Physics Instructor",
    email: "j.osei@westwood.edu",
    phone: "+1 555 0181",
    classrooms: 3,
    experience: "8 Years",
    avatar: "JO",
    avatarColor: "bg-indigo-500",
  },
  {
    id: "T003",
    name: "Mrs. Clara Higgins",
    dept: "Arts & Languages",
    title: "AP Literature Lecturer",
    email: "c.higgins@westwood.edu",
    phone: "+1 555 0182",
    classrooms: 5,
    experience: "15 Years",
    avatar: "CH",
    avatarColor: "bg-violet-500",
  },
  {
    id: "T004",
    name: "Mr. David Alston",
    dept: "Mathematics",
    title: "Algebra & Calculus Coach",
    email: "d.alston@westwood.edu",
    phone: "+1 555 0183",
    classrooms: 3,
    experience: "6 Years",
    avatar: "DA",
    avatarColor: "bg-amber-500",
  },
];
